src/commands/serve.ts
src/index.ts
src/utils/compile.ts

https://app.clickup.com/t/1za7nhv
depends on https://github.com/Frontify/frontify-cli/pull/171

fix(win32): Use join for paths and escape win32 input paths

---

src/commands/deploy.ts
src/utils/compile.ts

- use new marketplace endpoint
- use `extend` to allow uuid as object name ([doc](https://rollupjs.org/guide/en/#outputextend))
- fix issue where 2 blocks `const global` would collide

feat: use new marketplace endpoint

---

src/commands/deploy.ts
src/commands/login.ts

Fix 1: 
Allow hidden files to be uploaded to clarify
Fix 2:
Remove Content-Type header from function, since this is automatically appended by the httpClient if a request body is present.
https://github.com/Frontify/clarify/pull/11275 must be merged first

fix: enable hidden files

---

src/commands/serve.ts
src/index.ts

- Allow any IPs to access the dev server with `--allowExternal`
- Remove the `fs.strict = false` as [it has been fixed ](https://github.com/vitejs/vite/issues/2820)
- Remove unused type `Settings` as it has been moved to `@frontify/guideline-blocks-settings`

feat: allow external ips to access server

---

packages/app-bridge/src/AppBridgeBlock.ts
packages/app-bridge/src/types/Terrific.ts

Added
```ts
appBridge.openAssetChooser(
(result) => {
const assetsId = result.map((asset) => asset.id);
// [...]
appBridge.closeAssetChooser();
},
{
selectedValueIds: [1, 2, 3],
}
);
```
To test:
Build App Bridge with `pnpm build`
Link in your block `app-bridge`, `pnpm link <path to brand-sdk repo>/packages/app-bridge`

feat: add multiple ids to be selected in asset chooser

---

.changeset/four-cooks-trade.md
packages/cli/src/commands/deploy.ts

Windows users couldn't execute the `./node_modules/[...]` command due to slashes instead of backslashes

fix: deploy command on windows

---

.changeset/red-wasps-tap.md
packages/sidebar-settings/src/blocks/sectionHeading.ts

Add the possibility of having a heading that is asynchronously determined

feat: add async heading option for section

---

packages/app-bridge/src/react/useGuidelineActions.ts

Findings:
- move functions returned inconsistent data so it seemed best to remove all returns from move functions
- delete functions all returned undefined so not necessary to return data
- `updateDocumentGroup` and `updateCategory` return incomplete data so these are also not returned

feat: return data for useGuidelineActions functions

---

packages/app-bridge/src/AppBridgeBlock.spec.ts
packages/app-bridge/src/AppBridgeBlock.ts

This would go with https://github.com/Frontify/clarify/pull/14221
Basically we want to move the data return to be compatible with new endpoints (everything should be inside "data") => therefore we need the FE to expect the data from this legacy endpoint to be in data.
This is temporarily working with the old structure as well (can be removed after we deploy the clarify PR to all instances)

fix: read block settings from data object

---

.changeset/rude-garlics-notice.md
packages/app-bridge/src/AppBridgeBase.ts
packages/app-bridge/src/AppBridgeBlock.ts
packages/app-bridge/src/AppBridgeTheme.ts
packages/app-bridge/src/index.ts
packages/app-bridge/src/react/useBlockAssets.ts
packages/app-bridge/src/react/useDocumentCategories.ts
packages/app-bridge/src/react/useDocumentGroups.ts
packages/app-bridge/src/react/useDocumentPageTargets.spec.ts
packages/app-bridge/src/react/useDocumentPageTargets.tsx
packages/app-bridge/src/react/useDocumentPages.ts
packages/app-bridge/src/react/useDocumentSection.ts
packages/app-bridge/src/react/useDocumentTargets.spec.ts
packages/app-bridge/src/react/useDocumentTargets.tsx
packages/app-bridge/src/react/useDocuments.ts
packages/app-bridge/src/tests/AppBridgeBlockStub.ts

Adds AppBridgeBase interface to provide shared functionalities between `AppBridgeBlock` and `AppBridgeTheme`.
Implementation: https://github.com/Frontify/clarify/pull/14394/files

feat: add AppBridgeBase

---

.changeset/empty-rockets-sin.md
.changeset/mighty-waves-impress.md
packages/guideline-blocks-settings/package.json
packages/sidebar-settings/package.json
packages/sidebar-settings/src/blocks/choices.ts
packages/sidebar-settings/src/blocks/input.ts
pnpm-lock.yaml

Designers uses custom icons in the sidebar for themes... so we now need to support it 😬 
Remove the `devDependencies` strict version as it is only used in dev and pnpm will optimize the installation

feat: add custom icon support in segmented controls/dropdown/input

---

packages/app-bridge/src/AppBridgeTheme.ts
packages/app-bridge/src/react/usePageTemplateSettings.spec.ts
packages/app-bridge/src/react/usePageTemplateSettings.ts
packages/app-bridge/src/tests/AppBridgeThemeStub.ts

Renamed template `document` to `documentPage` (we moved the template settings on document page level)
Added:
- `updateDocumentPageTemplateSettings`
- `getLibraryPageTemplateSettings`
- `updateLibraryPageTemplateSettings`
Renamed:
- `getCoverPageSettings` to `getCoverPageTemplateSettings`
- `updateCoverPageSettings` to `updateCoverPageTemplateSettings`
- `getDocumentSettings` to `getDocumentPageTemplateSettings`
Make usage of the methods in the `usePageTemplateSettings` hook

refactor!: rename `document` to `documentPage` and add different methods

---

packages/app-bridge/src/types/Document.ts
packages/app-bridge/src/types/DocumentPage.ts

Document and DocumentPage targets come like: 
```
targets: [{
account_id: number;
asset_ids: unknown[];
created: string;
creator: number;
description: string;
group_ids: unknown[];
id: number;
modified: Nullable<unknown>;
modifier: Nullable<unknown>;
name: string;
sort: number;
total_groups: Nullable<unknown>;
total_links: Nullable<unknown>;
total_users: Nullable<unknown>;
user_ids: unknown[];
}]
```
and not like:
```
targets:[{
checked: boolean;
disabled: boolean;
indeterminate: boolean;
label: string;
target: {
account_id: number;
asset_ids: unknown[];
created: string;
creator: number;
description: string;
group_ids: unknown[];
id: number;
modified: Nullable<unknown>;
modifier: Nullable<unknown>;
name: string;
sort: number;
total_groups: Nullable<unknown>;
total_links: …
```

fix: incorrect document and document page targets type

---

packages/app-bridge/src/react/useBrandportalLink.spec.ts
packages/app-bridge/src/react/useBrandportalLink.ts
packages/app-bridge/src/react/useCoverPage.spec.ts
packages/app-bridge/src/react/useCoverPage.ts
packages/app-bridge/src/react/useDocumentCategories.ts
packages/app-bridge/src/react/useDocumentGroups.ts
packages/app-bridge/src/react/useDocumentPages.ts
packages/app-bridge/src/react/useDocuments.ts
packages/app-bridge/src/react/useGuidelineActions.ts
packages/app-bridge/src/tests/DocumentApiDummy.ts
packages/app-bridge/src/tests/DocumentCategoryApiDummy.ts
packages/app-bridge/src/tests/DocumentGroupApiDummy.ts
packages/app-bridge/src/types/Document.ts
packages/app-bridge/src/types/DocumentCategory.ts
packages/app-bridge/src/types/DocumentGroup.ts

- Added `enabled` to guideline hooks
- Added enriched fields `number_of_[...]` on `DocumentGroup`, `DocumentCategory` and `Document`
- Replaced `document_group_ids` on `Document` with the singular form
- Removed extra API call on `fetchDocuments`

feat: add `enabled` to hooks

---

.changeset/mean-dodos-return.md
packages/sidebar-settings/package.json
pnpm-lock.yaml

Get's rid of the old fondue version which results in an error when a block is being served with react 18.

chore(sidebar-settings): update fondue to support react 18

---

.changeset/five-mails-yell.md
packages/guideline-blocks-settings/package.json
pnpm-lock.yaml

Updates `@frontify/sidebar-settings` to have react 18 support

chore(guideline-block-settings): update sidebar settings

---

.changeset/chilly-vans-develop.md
packages/sidebar-settings/src/blocks/sectionHeading.ts

* added `hasSwitch` type to `sectionHeading`
* `hasSwitch` can be true or false and the defaultValue can be set. Leading us to three different states of section heading
1. switch on:
```
{
id: 'styleSection',
type: 'sectionHeading',
label: 'Section Heading with Switch',
hasSwitch: true,
defaultValue: true,
blocks: [
getBorderSettings(),
getGutterSettings({
id: 'isColumnGutterCustom',
dependentSettingId: COLUMN_NR_ID,
spacingChoiceId: SIMPLE_GUTTER_ID,
spacingCustomId: CUSTOM_GUTTER_ID,
defaultValueChoices: GutterSpacing.Auto,
}),
],
},
```
2. switch off
```
{
...
hasSwitch: true,
defaultValue: false,
blocks: [
...],
},
```
3. without switch
```
{
id: 'styleSection',
type: 'sectionHeading',
label: 'Section Heading',
blocks: [
...
],
},
```
**See usage in web-app: …

feat(sidebarSettings): add hasSwitch type to sectionHeading

---

packages/app-bridge/src/react/useCategorizedDocumentPages.spec.ts
packages/app-bridge/src/react/useCategorizedDocumentPages.ts
packages/app-bridge/src/react/useDocumentCategories.ts
packages/app-bridge/src/react/useDocumentGroups.ts
packages/app-bridge/src/react/useUncategorizedDocumentPages.spec.ts
packages/app-bridge/src/react/useUncategorizedDocumentPages.ts
packages/app-bridge/src/react/useUngroupedDocuments.ts

When a page is moved to the last position under its parent, it disappears.
Also some potential array mutations errors are fixed

fix: page moved to last position in the tree disappears

---

packages/app-bridge/package.json

Fixes for `useCategorizedDocumentPages` and `useUncategorizedDocumentPages.spec` regarding moving pages to last position

chore: bump app-bridge 3.0.0-beta.72

---

.changeset/tidy-needles-divide.md
packages/sidebar-settings/src/blocks/notification.ts

* `'general-settings.open'` type added to `NotificationFooterEvent`
This event will open these settings:
See implementation within web-app: https://github.com/Frontify/web-app/pull/329

feat(sidebarSettings): add footer event to notification block

---

.changeset/tame-bears-guess.md
packages/sidebar-settings/src/helpers/appendUnit.ts
packages/sidebar-settings/src/helpers/types.ts

adds [time](https://developer.mozilla.org/en-US/docs/Web/CSS/time) units so `appendUnit` can be used for animation/transition durations.

feat: add duration units to Unit type

---

packages/app-bridge/src/types/index.ts

This PR fixes a missing export of the type `PageTemplateAsset`.

fix: export PageTemplateAsset type

---

packages/app-bridge/src/AppBridgeTheme.ts
packages/app-bridge/src/tests/AppBridgeThemeStub.ts

This PR adds the missing methods to `AppBridgeTheme` for page template assets.

feat: add missing methods for page template assets

---

packages/app-bridge/src/react/useTemplateAssets.ts

This array fixes an issue that we don’t fetch assets when the hook has initially been rendered without a documentId and documentPageId.

fix: add documentId and documentPageId to dependency array

---

.changeset/ten-rats-mate.md
packages/guideline-blocks-settings/src/components/BlockItemWrapper/BlockItemWrapper.tsx

Ensuring that the BlockItemWrapper always returns an `Element`.
` error TS2786: 'BlockItemWrapper' cannot be used as a JSX component.`
@SamuelAlev maybe you see a better solution

fix: BlockItemWrapper return type

---

.changeset/bump-appbridge-version.md

To publish a version with the v90 app-bridge.

chore: bump appbridge version

---

packages/guideline-blocks-settings/package.json
pnpm-lock.yaml

I think accidentally fondue got downgraded to 11.3 at [Commit](https://github.com/Frontify/brand-sdk/commit/6c5d4f63ef8c5995790aa444dc29469b095d63ba)
Should resolve that

revert: fondue downgrade

---

.changeset/shy-keys-promise.md
packages/guideline-blocks-settings/src/components/BlockItemWrapper/BlockItemWrapper.tsx

Fixes a compatibility if you were tabbing through elements 
So we need to higher the `z-index` to 60 (cm toolbar is 50), so its higher as the content manager

fix: blockItemWrapper Toolbar z-index

---

.changeset/wise-hotels-heal.md
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/components/FloatingButton/EditButtonModal/EditModal.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/EditLinkModal/EditModal.tsx

The edit modals were using the `BlockStyles.p` styles, which can be white color. My opinion is that the RTE edit modal styles should be consistent, regardless of the design settings, as that is only used for editing. Open for debating.
[23021/TASK-8529](https://app.clickup.com/t/2523021/TASK-8529)

fix(RTE): edit modal styles can be invisible

---

.changeset/empty-monkeys-hang.md
packages/guideline-blocks-settings/src/components/RichTextEditor/SerializedText.tsx

Plate adds by default `white-space: pre-wrap` around everything and this was missing and made the numbers jumping.
[Loom](https://www.loom.com/share/1e2751dc68f949f9a6ab63f2a67f3aed)
[Task](https://app.clickup.com/t/8692pynn1)

fix: RTE inconsistent numbered list style

---

.changeset/tiny-wasps-arrive.md
packages/guideline-blocks-settings/src/components/Link/LinkSelector/DocumentLink.tsx
packages/guideline-blocks-settings/src/components/Link/LinkSelector/DocumentLinks.tsx
packages/guideline-blocks-settings/src/components/Link/LinkSelector/LinkSelector.spec.ct.tsx
packages/guideline-blocks-settings/src/components/Link/LinkSelector/LoadingIndicator.tsx
packages/guideline-blocks-settings/src/components/Link/LinkSelector/PageLink.tsx
packages/guideline-blocks-settings/src/components/Link/LinkSelector/PageLinks.tsx
packages/guideline-blocks-settings/src/components/Link/LinkSelector/SectionLink.tsx

onClick and onFocus did the same thing, so initial click on a link item resulted in toggling it twice => essentially canceling the action.
Removed the onFocus handlers, and changed the arrow buttons to be <button> elements so the link chooser is still accessible.
https://www.loom.com/share/309c34b38c6c4a94a84cd1177ac6a848

fix(LinkSelector): initial click triggers twice

---

packages/app-bridge/src/react/usePlatformAppBridge.spec.ts
packages/app-bridge/src/react/usePlatformAppBridge.ts

…ws easier handling in the app. 
@getflourish 
Now we can do 
```
const appBridge = usePlatformAppBridge();
[…]
const context = appBridge?.context().get();
```

fix: update react hook to return undefined and appBridge

---

CODEOWNERS

Currently G2 is still owner of the types in the brand sdk. From my understanding this should now also be part of ecosystem.
Also I saw that for Web-App and App-Server the Codeowners file is owned by the architecture team. I assume, this should be the same here, right?

chore: make the ecosystem team the code owner of the types

---

.changeset/curly-tips-turn.md
packages/cli/src/commands/deploy.ts

Just had a case in which an agency had the manifest.json in the `.gitignore`, so the file wasn't deployed and the Block data wasn't updated. So this PR just filters the `manifest.json` out of the `gitignoreEntries`, so it's never a problem. 
More Context:
- They deploy the Block on multiple instances and have an AppId for each, so they have multiple `manifest.json`'s 
- So they have a script deploy:instanceA which then renames the instancea.manifest.json to manifest.json and deploys

fix(cli): never ignore manifest.json

---

.changeset/clean-tips-invent.md
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar.tsx

fix(BlockItemWrapper): fix toolbar focus style

---

.changeset/warm-apples-press.md
packages/cli/src/commands/serve.ts
packages/cli/src/utils/appBridgeVersion.ts
packages/cli/src/utils/compiler.ts
packages/cli/src/utils/index.ts
packages/cli/src/utils/npm.ts
packages/cli/tests/files/compile-test-files/package.json
packages/cli/tests/utils/appBridgeVersion.spec.ts
packages/cli/tests/utils/compiler.spec.ts

Adds the appBridge version to the window. 
`serve`: `window.DevCustomBlock.dependencies.appBridge`
`deploy`: `window.<appId>.dependencies['@frontify/app-bridge']`
[Task](https://app.clickup.com/t/869309vxt)

feat(cli): add app bridge version to build

---

packages/app-bridge/src/registries/api/GetAssetBulkDownloadToken.ts

- We need to rename this helper method as there's an existing method with the same name in `web-app` to avoid the following error:
```
TS2308: Module './repositories' has already exported a member named 'getAssetBulkDownloadToken'. Consider explicitly re-exporting to resolve the ambiguity.
```

chore: Rename Bulk Asset download helper

---

.changeset/popular-points-bathe.md
packages/cli/templates/content-block-css-modules/package.json
packages/cli/templates/content-block-css/package.json
packages/cli/templates/content-block-tailwind/package.json
packages/cli/templates/platform-app-css-modules/package.json
packages/cli/templates/platform-app-css/package.json
packages/cli/templates/platform-app-tailwind/package.json

Should be merged and released after (or the same time), with: https://github.com/Frontify/brand-sdk/pull/620

chore(cli): templates use stable version

---

.changeset/new-bobcats-leave.md
.changeset/three-flies-repeat.md
packages/guideline-blocks-settings/src/components/BlockItemWrapper/types.ts

Export a type for use in guidelines Template Block
Avoids having to duplicate the type here https://github.com/Frontify/guideline-blocks/pull/699/files#diff-830e07fe3324d4770dcc0c70549882a588f45cb1b829989ba044709b46eebfde

feat: export type for use in template block

---

.changeset/unlucky-mice-give.md
packages/cli/src/utils/compiler.ts

There was a bug inside of the Platform App compiler with a mapping of the generated js files.

fix: platform app compiler

---

.changeset/spicy-apricots-guess.md
packages/cli/src/utils/compiler.ts

- js and css hashed filename was switched.

chore: fix css and js filename exchanged

---

.changeset/thick-lizards-visit.md
packages/guideline-blocks-settings/src/components/Attachments/Attachments.tsx
packages/guideline-blocks-settings/src/components/Attachments/AttachmentsButtonTrigger.tsx
packages/guideline-blocks-settings/src/components/Attachments/types.ts
packages/guideline-blocks-settings/src/components/BlockItemWrapper/BlockItemWrapper.tsx
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar.tsx
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/Toolbar.spec.tsx
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/Toolbar.tsx
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/ToolbarAttachments.tsx
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/ToolbarAttachmentsTrigger.tsx
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/ToolbarSegment.tsx
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/helpers.ts
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/index.ts
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/types.ts
packages/guideline-blocks-settings/src/components/BlockItemWrapper/types.ts
packages/guideline-blocks-settings/src/hooks/useAttachments.spec.tsx
packages/guideline-blocks-settings/src/hooks/useAttachments.tsx

To Test: 
- `pnpm build`
- `cd packages/guideline-blocks-settings`
- `pnpm link --global`
(In guideline-blocks/packages/audio)
- checkout https://github.com/Frontify/guideline-blocks/pull/702 branch (fix/audio-block-update)
- `pnpm link --global @fronfify/guideline-blocks-settings`
- `pnpm serve`

feat: update block toolbar to include attachments flyout

---

packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/ToolbarAttachments.tsx

Fixes an issue introduced in https://github.com/Frontify/brand-sdk/pull/672 where the `onAddAttachments` method was renamed `onAttachmentsAdd` but not renamed in the BlockToolbar

fix: typeerror in toolbar 

---

.changeset/curly-readers-clean.md
packages/guideline-blocks-settings/src/components/Attachments/Attachments.spec.ct.tsx
packages/guideline-blocks-settings/src/components/Attachments/Attachments.tsx

As preparation to move the `@frontify/app-bridge` to the peerDeps we need to replace all deprecated functions.

chore: replace deprecated functions in attachments

---

.changeset/modern-turtles-cheat.md
packages/guideline-blocks-settings/src/components/Attachments/AttachmentsButtonTrigger.tsx

Prevent Attachments standalone button from being affected by line height changes in global design settings, so that it matches download button height

fix: add forced line height to button

---

.changeset/slimy-bikes-sin.md
packages/guideline-blocks-settings/package.json
pnpm-lock.yaml

There will be a follow up PR to adjust the CI Matrix (as soon 4.0.0 alpha is released)

feat(GuidelineBlocksSettings): add support for app-bridge alpha

---

.changeset/green-dryers-sip.md
packages/app-bridge/.gitignore
packages/app-bridge/package.json
pnpm-lock.yaml

Adds a `package.json.d.ts`, useful to compare and infer version in external package.
TypeScript doesn't allow `as const` when importing from a `json` file thus this is the only way to get full inferring of types :/

chore: add typing for package.json

---

.github/workflows/guideline-blocks-continuous-integration.yml
packages/guideline-blocks-settings/src/components/DownloadButton/DownloadButton.tsx

- adds latest 3 to test matrix
first alpha 4 needs to be added after we have released `app-bridge: 4.0.0-alpha.1`
See them run: https://github.com/Frontify/brand-sdk/actions/runs/7656508195?pr=718

ci: add latest 3 to matrix

---

.github/workflows/guideline-blocks-continuous-integration.yml
packages/guideline-blocks-settings/src/components/DownloadButton/DownloadButton.tsx

- adds first 4.0.0-alpha and also the last one
All tests are running see: https://github.com/Frontify/brand-sdk/actions/runs/7656116703?pr=717

ci: add alpha (first and latest) to the matrix

---

.changeset/five-apples-impress.md
packages/cli/src/commands/deploy.ts

On windows, paths contain `\\` and are interpreted as [escape characters](https://github.com/mrmlnc/fast-glob#advanced-syntax) by `fastGlob`, which causes it to ignore all files. This fix replaces the `join` function with `fastGlob`s `convertPathToPattern` [method](https://github.com/mrmlnc/fast-glob#convertpathtopatternpath) where applicable.

fix: properly handle paths on windows

---

.changeset/thin-bears-press.md
packages/cli/src/commands/deploy.ts
packages/cli/src/index.ts
packages/cli/src/utils/user.ts
packages/cli/tests/utils/user.spec.ts

This change makes it possible to deploy without the need to run `login` first. You can pass `--instance` and `--token` to the `deploy` command, and it will use those values instead of relying on the stored config.

feat: add deploy token

---

.changeset/dull-games-cross.md
packages/guideline-blocks-settings/package.json

Else it doesn't works with a tsconfig containing 
```
"module": "ESNext",
"moduleResolution": "bundler",
```

fix: add missing `types` entry in exports list

---

.changeset/config.json
package.json
pnpm-lock.yaml

bumps `@changesets/changelog-github` and `@changesets/cli`
and adjusts the config:
```
"___experimentalUnsafeOptions_WILL_CHANGE_IN_PATCH": {
"onlyUpdatePeerDependentsWhenOutOfRange": true
},
``` 
Its the same config as on dev branch where its working properly
See last release on dev branch https://github.com/Frontify/brand-sdk/pull/716/

ci: fix changeset onlyUpdatePeerDepsWhenOutOfRange

---

.changeset/khaki-wasps-learn.md
packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/MenuToolbarButton/index.ts

Export missing type to make it cleaner to create menu item arrays outside of the package

fix: export menu component and type

---

packages/app-bridge/src/AppBridgeTheme.ts
packages/app-bridge/src/react/useGuidelineActions.spec.ts
packages/app-bridge/src/react/useGuidelineActions.ts
packages/app-bridge/src/tests/AppBridgeThemeStub.ts
packages/app-bridge/src/tests/DocumentPageDummy.ts
packages/app-bridge/src/types/DocumentPage.ts

This PR uses the new page duplication endpoint and drops the usage of the legacy endpoint.
Follow-up of: https://github.com/Frontify/app-server/pull/18390
Pre-requisite of: https://github.com/Frontify/web-app/pull/2916

feat: use new page duplication endpoint

---

.changeset/strong-tools-check.md
packages/app-bridge/src/AppBridgePlatformApp.ts

- i noticed that sometimes the app couldnt connect to the web-app, as there is a interfering notify object.
{msgId: '17pvzfy', source: 'poa7ru', destination: '1033kkb', name: 'should-intercept-webauthn', type: 'op-window-direct-response', …}
Why that happens i could not figure out and also not what this event is. Now when there is an intercepting event the subscribe will do a retry of X times.

fix: add retry to subscription

---

.changeset/strong-tools-check.md

fixes the changeset so guideline-blocks-settings are not getting released..

chore: changeset remove guideline-blocks-settings

---

.changeset/pretty-items-marry.md
packages/app-bridge/src/react/useGroupedDocuments.spec.ts
packages/app-bridge/src/react/useUngroupedDocuments.spec.ts

try to fix these flaky tests: `useGroupedDocuments` and `useUngroupedDocuments`
CU-8693wzzx6

fix: flaky useUngroupedDocuments and useGroupedDocuments tests

---

.changeset/fair-seahorses-look.md
packages/sidebar-settings/src/blocks/assetInput.ts

Adds prop to assetInput to allow showing the `Delete/Remove` option in the assetInputBlock

feat: assetInput allowDelete prop

---

.github/workflows/app-bridge-continuous-integration.yml
.github/workflows/cli-continuous-integration.yml
.github/workflows/continuous-deployment.yml
.github/workflows/guideline-blocks-continuous-integration.yml
.github/workflows/typing-continuous-integration.yml

As `pnpm` 9 got released the CI breaks now as it was defined as latest, will pin it down till we update it 
To unblock: https://github.com/Frontify/brand-sdk/pull/860

ci: pin pnpm to 8

---

.changeset/giant-dodos-work.md
packages/app-bridge/src/react/usePageTemplateSettings.spec.ts
packages/app-bridge/src/react/usePageTemplateSettings.ts

This is needed so we can know settings not belonging to ThemeSettings but only to pageTemplateSettings

feat: usePageTemplateSettings to return templateThemeSettings

---

.changeset/hip-gorillas-explode.md
packages/app-bridge/src/tests/TemplateDummy.ts
packages/app-bridge/src/types/Template.ts

Adds the `creationFromUri` type to the `Templates` type so that it is manageable via the `web-app` and accessible in the `TemplateBlock`.

feat(Templates): add creation form uri to template type

---

packages/app-bridge/src/react/useDocumentNavigation.spec.ts
packages/app-bridge/src/react/useDocumentNavigation.ts
packages/app-bridge/src/react/usePortalNavigation.spec.ts
packages/app-bridge/src/react/usePortalNavigation.ts

This fixes a bug that causes the debounce callback not to be called from some event listeners.

fix: wrap debounce in `useMemo`

---

.changeset/calm-candles-wink.md
packages/app-bridge/src/AppBridgePlatformApp.spec.ts
packages/app-bridge/src/AppBridgePlatformApp.ts
packages/app-bridge/src/react/usePlatformAppBridge.spec.ts
packages/app-bridge/src/window.d.ts

The PlatformApp AppBridge should be only created once, but multiple times callable from child-Components. 
Added global interface on the window Object for appBridgePlatformApp.
Intended behaviour: 
```
ParentComponet: 
const appBridge = usePlatformAppBridge();
return <ChildComponent />
ChildComponent: 
// should return the same reference to have consistent state / context
const appBridge = usePlatformAppBridge();
`

feat: only one app bridge per iframe

---

.changeset/fresh-maps-agree.md
packages/cli/src/utils/verifyManifest.ts
packages/cli/tests/utils/verifyManifest.spec.ts

-> reimplement the change that went by  mistake on dev. 
-> adjusts the regex to be more strict with the naming for platformApp Secrets

feat: change regex on main

---

.changeset/sour-pumpkins-suffer.md
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/components/ButtonToolbarButton.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/LinkPlugin/LinkToolbarButton.tsx

This prevents some anomalies that caused Safari to not open link toolbar on first click

fix(RTE): on safari the first click is not recognized

---

.changeset/fair-foxes-train.md
packages/app-bridge/src/tests/DocumentSectionApiDummy.ts
packages/app-bridge/src/types/DocumentSection.ts

These properties are not used externally (The `DocumentSection` type should be used externally)

chore: remove unnecessary properties on DocumentSectionApi

---

.changeset/fluffy-files-kiss.md
packages/guideline-blocks-settings/package.json
packages/guideline-blocks-settings/tailwind.config.ts
pnpm-lock.yaml

When using the new tailwind preset, the dependency is missing from the consumer. With this PR I aim to include `@tailwindcss/container-queries` in the bundle, so the consumer does not have to install it.

fix(*): container query plugin is not a public dependency

---

packages/app-bridge-theme/src/types/Guideline.ts

This PR adds the `GuidelineBrandPortalLink` interface that later can be used by Themes.

feat(AppBridgeTheme): added GuidelineBrandPortalLink interface

---

.changeset/dry-mangos-fix.md
packages/app-bridge-theme/src/AppBridgeTheme.ts
packages/app-bridge-theme/src/registries/CommandRegistry.ts
packages/app-bridge-theme/src/types/Command.ts

- Added a `command` property in CommandRegistry.
- Removed obsolete `Command` type. It was used to strip away non-AppBridgeTheme commands, but that is no longer necessary with a separate package. Will also enable us to bring more clarity into the implementation, where we often mix `Command` and `CommandRegistry`, despite being identical
- Removed aliases for payload types. Without aliases the actually required type is more transparent, instead of being hidden by an alias
- Moved `CommandNameValidator` type to internal only

feat(app-bridge-theme): add a navigate command

---

.changeset/spotty-papayas-admire.md
packages/guideline-blocks-settings/src/components/Attachments/Attachments.spec.ct.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/RichTextEditor.spec.ct.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/RichTextEditor.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/SerializedText.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ColumnBreakPlugin/ColumnBreakPlugin.ts
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ColumnBreakPlugin/helper.spec.ts
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ColumnBreakPlugin/helpers.ts
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ColumnBreakPlugin/index.ts
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/index.ts
packages/guideline-blocks-settings/src/components/RichTextEditor/types.ts

Introducing container query responsivity to the rich text editor when it comes to columns.
1. Extending fondue ColumnBreak plugin with some custom logic, so guideline-blocks can stay untouched
2. Extending serialized text with the same logic

feat(RTE): add custom column break plugin

---

.changeset/curly-lizards-know.md
packages/guideline-blocks-settings/src/components/RichTextEditor/RichTextEditor.spec.ct.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ColumnBreakPlugin/helpers.ts

Changes made according to [this loom](https://www.loom.com/share/814d70588956404c9f1a82200f768796).
1. Now we always wrap immediately to 1 column, no in-between.
2. When wrapping to 1-column, disable the specified column break if there is any.

fix(RTE): avoid column breaks when wrapping

---

.changeset/hip-foxes-listen.md
packages/app-bridge/src/react/useDocumentCategories.spec.ts
packages/app-bridge/src/react/useDocumentNavigation.spec.ts
packages/app-bridge/src/react/useGuidelineActions.ts
packages/app-bridge/src/types/Emitter.ts

`documentId` needs to be included in `GuidelineDocumentCategory` events payload for themes to be aware of changes from the Navigation Manager and update navigation items for the document.
https://app.clickup.com/t/8694xwktr

feat: add documentId to GuidelineDocumentCategory event payload

---

.changeset/stale-lizards-watch.md
packages/guideline-blocks-settings/src/components/RichTextEditor/RichTextEditor.spec.ct.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/components/FloatingButton/CustomFloatingButton.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/components/FloatingButton/EditButtonModal/EditModal.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/CustomFloatingLink.tsx
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/EditLinkModal/EditModal.tsx

1. Use portals to render the floating modals
2. Add little gap in edit modal so it is not cluttered anymore
https://app.clickup.com/t/86952var1

fix(RTE): floating modals are hidden behind higher z index siblings

---

packages/app-bridge-theme/src/registries/CommandRegistry.ts
packages/app-bridge-theme/src/registries/commands/AiBrandAssistantDialog.ts
packages/app-bridge-theme/src/registries/commands/index.ts
packages/app-bridge-theme/src/types/Context.ts

This PR adds 2 commands to the AppBridgeTheme:
- `openAiBrandAssistantDialog`
- `closeAiBrandAssistantDialog`

feat(AppBridgeTheme): added commands to open/close AIBrandAssistant dialog

---

.changeset/four-ravens-try.md
packages/guideline-themes/package.json
packages/guideline-themes/src/index.ts

Partially reverts changes in https://github.com/Frontify/brand-sdk/pull/1103
Intersected type `ContentAreaSettings` complicates typing for devs
https://app.clickup.com/t/8695hb071

fix(guideline-themes): export types ungroupped

---

.changeset/itchy-months-teach.md
packages/sidebar-settings/src/blocks/dropdown.ts

New implementation of the dropdownBlock doesn't use `size` prop anymore

feat: deprecate dropdownBlock size prop

---

.changeset/friendly-olives-shake.md
packages/guideline-blocks-settings/src/hooks/useDndSensors.ts

Through painful trial and errors I found that the `useDndSensor` is causing the scroll to stop midway. Possibly due to the dnd-kit using some internal scroll listener, and the `useSensor` hook was recreated on every render since the second parameter was not memoised.
https://app.clickup.com/t/2523021/TASK-12175

fix(*): scroll events are hijacked by dnd-kit

---

.changeset/fast-eagles-notice.md
packages/guideline-blocks-settings/src/styles.css

Otherwise it's possible that `web-app` fondue is on a newer version and does not have the appropriate CSS module styles anymore because the hash changed.

feat(*): add fondue component style css

---

.changeset/two-dolls-joke.md
packages/cli/src/utils/file.ts

Issue:
When creating an app with the frontify-cli, the .gitignore file is missing. The missing file makes deployment to the marketplace fail. Although it can be easily added manually, it should be added by default for a better DX.
Why it's missing even if it exist in the templates files:
`.gitignore` files are ignored by default when a package is published to `npm`. [See docs for reference.](https://docs.npmjs.com/cli/v9/using-npm/developers#keeping-files-out-of-your-package) 
Possible Solution:
Manually write a .gitignore file (generic template) when the files are copied from source to destination folder.

fix: gitignore file missing when creating an app

---

.changeset/empty-jobs-add.md
packages/guideline-themes/src/index.ts

[CU-86966vzkv Change the settings structure type in BrandSDK](https://app.clickup.com/t/86966vzkv)

refactor(guideline-themes): removes themeConfigExport.settings

---

packages/app-bridge-app/src/AppBridgePlatformApp.ts
packages/app-bridge-app/src/registries/api/ApiMethodRegistry.ts
packages/app-bridge-app/src/registries/api/ExecuteSecureRequest.spec.ts
packages/app-bridge-app/src/registries/api/ExecuteSecureRequest.ts
packages/app-bridge-app/src/registries/api/index.ts
packages/app-bridge-app/src/utilities/MessageBus.spec.ts
packages/app-bridge-app/src/utilities/MessageBus.ts

This PR creates a new `executeSecureRequest` command that returns a [fetch response](https://developer.mozilla.org/en-US/docs/Web/API/Response). 
The client benefits from being able to decide what to do with the data. For example, deciding whether it's an image or not.
Since it's not possible to send complex objects with methods via `MessagePort:postMessage()`, we have to disassemble the message before sending it through the port and reassemble it on the other side.

feat(app-bridge-app): New command `executeSecureRequest`

---

.changeset/big-maps-marry.md
packages/cli/templates/content-block-css-modules/package.json
packages/cli/templates/content-block-css/package.json
packages/cli/templates/content-block-tailwind/package.json
packages/cli/templates/platform-app-css-modules/package.json
packages/cli/templates/platform-app-css/package.json
packages/cli/templates/platform-app-tailwind/package.json

Otherwise `npm i` bumps it up to 5.0.0 which is breaking when served

feat(templates): add zustand as peerdependency

---

.changeset/brave-comics-guess.md
packages/app-bridge/src/react/useBlockTemplates.spec.ts
packages/app-bridge/src/react/useBlockTemplates.ts

TASK-12885
This fixes an issue where a request to delete existing template ids before adding new ones returned an error if an empty array was submitted in the request parameter.

fix(templates): prevent delete on update without existing template ids

---

.changeset/thirty-chicken-play.md
packages/app-bridge-app/src/react/appContext.ts

-> uses the platformAppContext instead of the single contexts to help with typing.

feat: add context instead of single contexts

---

.changeset/curvy-steaks-rush.md
packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/utils/styles.ts

fix(RTE): button text overflow

---

.changeset/nice-hornets-deny.md
packages/guideline-blocks-settings/src/components/BlockItemWrapper/BlockItemWrapper.tsx

fix(BlockItemWrapper): Adjust block item wrapper outline offset

---

.changeset/eight-candles-agree.md
packages/sidebar-settings/src/blocks/choices.ts

Reverts Frontify/brand-sdk#1194

fix: Revert "feat(sidebar-settings): add optional aria-label to Choice type"

---

.changeset/strange-radios-bow.md
packages/app-bridge-theme/src/AppBridgeTheme.ts
packages/app-bridge-theme/src/types/State.ts
packages/app-bridge-theme/src/types/index.ts

This will enable theme developers to store the height of any sticky elements on top of the page. The sticky elements' size is needed in web-app for properly being able to determine when a heading is in view and to be able to reliably scroll a heading to the top of the content area.

feat: introduce state to AppBridgeTheme

---

README.md

The current links led to outdated documentation

chore(Readme): update documentation links

---

.changeset/pretty-turkeys-roll.md
cypress/support/component.ts
packages/guideline-blocks-settings/package.json
packages/guideline-blocks-settings/src/components/Link/LinkInput.spec.ct.tsx
packages/guideline-blocks-settings/src/styles.css
packages/guideline-blocks-settings/tailwind.config.ts
pnpm-lock.yaml

I linked it together with guideline blocks and it's working nicely. However the new tokens need to be injected into web-app. For this we might need to tweak the `scope.js` if we want to do it on a per block basis, because right now `:root:` variables are scoped to a block, which means in portalled components it is not properly styled. E.g. tooltips don't have background color.
So we either inject in web-app and rely on the variables being present there, or tweak the `scope.js` to insert the `:root` variables globally, or at least into modal components. E.g. `.image-block, [data-radix-popper] { /* new tokens */ }`

chore: bump fondue to v13
