package-lock.json, package.json
`Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h`
=> fix: update minimist package

src/commands/deploy.ts, src/commands/login.ts, src/index.ts
Automatically use the instance set in the login command
=> feat: remove instance parameter in deploy command

packages/app-bridge/package.json, packages/app-bridge/src/react/useBlockAssets.spec.ts, packages/app-bridge/src/react/useColorPalettes.spec.ts, packages/app-bridge/src/react/useColors.spec.ts, pnpm-lock.yaml
Update to React 18 and update testing library
=> chore: update react 18

.changeset/loud-ghosts-reply.md, packages/app-bridge/src/utilities/color.spec.ts, packages/app-bridge/src/utilities/color.ts, packages/app-bridge/src/utilities/index.ts, packages/guideline-blocks-settings/src/index.ts, packages/sidebar-settings/src/blocks/choices.ts, packages/sidebar-settings/src/blocks/fontInput.ts, packages/sidebar-settings/src/blocks/index.ts, packages/sidebar-settings/src/blocks/input.ts
In combination with https://github.com/Frontify/clarify/pull/13267
Add font input type
Add color utilities
=> feat: font input

.changeset/three-vans-reply.md, packages/sidebar-settings/src/blocks/assetInput.ts, packages/sidebar-settings/src/blocks/base.ts, packages/sidebar-settings/src/blocks/checkbox.ts, packages/sidebar-settings/src/blocks/checklist.ts, packages/sidebar-settings/src/blocks/choices.ts, packages/sidebar-settings/src/blocks/colorInput.ts, packages/sidebar-settings/src/blocks/dropdown.ts, packages/sidebar-settings/src/blocks/fontInput.ts, packages/sidebar-settings/src/blocks/input.ts, packages/sidebar-settings/src/blocks/linkChooser.ts, packages/sidebar-settings/src/blocks/multiInput.ts, packages/sidebar-settings/src/blocks/notification.ts, packages/sidebar-settings/src/blocks/sectionHeading.ts, packages/sidebar-settings/src/blocks/slider.ts, packages/sidebar-settings/src/blocks/switch.ts, packages/sidebar-settings/src/blocks/templateInput.ts, packages/sidebar-settings/src/blocks/textarea.ts, packages/sidebar-settings/src/bundle.ts, packages/sidebar-settings/src/helpers/appendUnit.ts, packages/sidebar-settings/src/helpers/presetCustomValue.ts
Add a few word on properties of the sidebar.
In the future, it will have link to the documentation but that is a good start.
=> chore: add JSDoc

packages/app-bridge/src/AppBridgeBlock.spec.ts, packages/app-bridge/src/AppBridgeTheme.spec.ts, packages/app-bridge/src/AppBridgeTheme.ts, packages/app-bridge/src/react/useBrandportalLink.spec.ts, packages/app-bridge/src/react/useCoverPage.spec.ts, packages/app-bridge/src/react/usePageTemplateSettings.spec.ts, packages/app-bridge/src/react/usePageTemplateSettings.ts, packages/app-bridge/src/repositories/DocumentRepository.ts, packages/app-bridge/src/tests/AppBridgeBlockStub.ts, packages/app-bridge/src/tests/AppBridgeThemeStub.ts, packages/app-bridge/src/types/Emitter.ts, packages/app-bridge/src/window.d.ts
Add support for document and library settings
=> feat: add document and library settings

packages/app-bridge/src/AppBridgeTheme.ts, packages/app-bridge/src/tests/AppBridgeThemeStub.ts, packages/app-bridge/src/tests/GuidelineSearchResultApiDummy.ts, packages/app-bridge/src/tests/GuidelineSearchResultDummy.ts, packages/app-bridge/src/types/GuidelineSearchResult.ts, packages/app-bridge/src/types/index.ts
Add the signature for guideline search (theme only for now)
=> feat: add guideline search signature

.changeset/chilled-bobcats-change.md, packages/guideline-blocks-settings/package.json, pnpm-lock.yaml
Update @frontify/sidebar-settings to get react 18 support
=> chore(guideline-block-settings): update @frontify/sidebar-settings

packages/app-bridge/package.json
chore: release app-bridge 3.0.0-beta.71
=> chore: bump app-bridge 3.0.0-beta.71

packages/app-bridge/src/react/useDocumentCategories.ts, packages/app-bridge/src/react/useDocumentGroups.spec.ts, packages/app-bridge/src/react/useDocumentGroups.ts, packages/app-bridge/src/react/useGroupedDocuments.spec.ts, packages/app-bridge/src/react/useGroupedDocuments.ts, packages/app-bridge/src/react/useUngroupedDocuments.spec.ts, packages/app-bridge/src/react/useUngroupedDocuments.ts
Prevents error trying to update a read-only item
This solves the issues:
- https://app.clickup.com/t/867838ktc
- https://app.clickup.com/t/867838qf9
=> fix: inmutable items error

.changeset/nine-boats-sell.md, packages/guideline-blocks-settings/src/index.ts
Type adjustment to reflect possiblity to have functions as settings input
=> feat(settings): add type for function settings

packages/app-bridge/src/react/useCategorizedDocumentPages.ts, packages/app-bridge/src/react/useDocumentCategories.spec.ts, packages/app-bridge/src/react/useDocumentCategories.ts, packages/app-bridge/src/react/useDocumentGroups.spec.ts, packages/app-bridge/src/react/useDocumentGroups.ts, packages/app-bridge/src/react/useGroupedDocuments.spec.ts, packages/app-bridge/src/react/useGroupedDocuments.ts, packages/app-bridge/src/react/useGuidelineActions.spec.ts, packages/app-bridge/src/react/useGuidelineActions.ts, packages/app-bridge/src/react/useUncategorizedDocumentPages.ts, packages/app-bridge/src/react/useUngroupedDocuments.spec.ts, packages/app-bridge/src/react/useUngroupedDocuments.ts, packages/app-bridge/src/tests/DocumentCategoryDummy.ts, packages/app-bridge/src/tests/DocumentGroupDummy.ts, packages/app-bridge/src/types/Emitter.ts
Process the sorting for the UI until the API responds and confirms the sorting.
=> feat: NM re-positioning preview

packages/app-bridge/src/react/useCategorizedDocumentPages.ts, packages/app-bridge/src/react/useDocumentCategories.spec.ts, packages/app-bridge/src/react/useDocumentCategories.ts, packages/app-bridge/src/react/useDocumentGroups.spec.ts, packages/app-bridge/src/react/useDocumentGroups.ts, packages/app-bridge/src/react/useGroupedDocuments.spec.ts, packages/app-bridge/src/react/useGroupedDocuments.ts, packages/app-bridge/src/react/useUncategorizedDocumentPages.ts, packages/app-bridge/src/react/useUngroupedDocuments.spec.ts, packages/app-bridge/src/react/useUngroupedDocuments.ts
refactoring the logic for preview sorting items. Cleaner and more reliable
=> feat: optimized and cleaner position preview

packages/app-bridge/src/react/useGuidelineActions.spec.ts
With these tests added, the coverage for useGuidelineActions goes up to 95.23%:
=> feat: add missing useGuidelineActions tests

packages/app-bridge/src/types/PageTemplateAsset.ts
This PR adds the types for PageTemplateAssets.
=> feat: add PageTemplateAsset types

.changeset/brave-rocks-return.md, packages/guideline-blocks-settings/src/components/RichTextEditor/serializer/nodes/button.ts, packages/guideline-blocks-settings/src/components/RichTextEditor/serializer/nodes/checkItemNode.ts, packages/guideline-blocks-settings/src/components/RichTextEditor/serializer/nodes/default.ts, packages/guideline-blocks-settings/src/components/RichTextEditor/serializer/nodes/link.ts, packages/guideline-blocks-settings/src/components/RichTextEditor/serializer/serializeNodesToHtmlRecursive.ts
=> feat(RTE): add dir to serializer

packages/app-bridge/src/react/index.ts
This PR exports the useThemeSettings hook
=> feat: export useThemeSettings

.changeset/modern-baboons-appear.md, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar.tsx
Fix the toolbar so it's consistent with the one of the content manager
=> fix: focus ring consistence

.changeset/friendly-stingrays-jam.md, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/ButtonMarkupElement/ButtonMarkupElementNode.tsx, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/components/FloatingButton/InsertButtonModal/InsertButtonModal.tsx, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/createButtonPlugin.ts, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/utils/styles.ts
add margin-top/bottom to buttons so they behave the same as in the old RTE
=> fix: buttonPlugin margins

packages/app-bridge/package.json, packages/app-bridge/src/AppBridgePlatformApp.spec.ts, packages/app-bridge/src/AppBridgePlatformApp.ts
Web-App Part https://github.com/Frontify/web-app/pull/1241
=> feat: add localContext set in init and add get / subscribe methods.

packages/app-bridge/src/utilities/MessageBus.ts
Increased timeout to have more time for asset Processing
=> chore: increase timeout

.changeset/tough-dolphins-hang.md, package.json, packages/guideline-blocks-settings/package.json, packages/sidebar-settings/package.json, pnpm-lock.yaml
=> chore: bump fondue to 341

packages/app-bridge/src/registries/api/ApiMethodRegistry.ts, packages/app-bridge/src/registries/api/CreateAsset.spec.ts, packages/app-bridge/src/registries/api/CreateAsset.ts, packages/app-bridge/src/registries/api/GetAssetResourceInformation.spec.ts, packages/app-bridge/src/registries/api/GetAssetResourceInformation.ts, packages/app-bridge/src/registries/api/GetCurrentUser.spec.ts, packages/app-bridge/src/registries/api/GetCurrentUser.ts, packages/app-bridge/src/registries/api/index.ts
- renames api call and adds helpers for all api calls
=> feat: add api helper

packages/app-bridge/package.json, packages/app-bridge/src/AppBridgePlatformApp.ts, packages/app-bridge/src/registries/api/ApiMethodRegistry.ts, packages/app-bridge/src/registries/api/CreateAsset.ts, packages/app-bridge/src/registries/api/GetAssetResourceInformation.ts
- Update helper functions to return specific method name
- Bump to release new version
=> fix: add specific typing to helper return

.changeset/nine-glasses-dress.md, packages/cli/templates/content-block-css-modules/src/settings.ts, packages/cli/templates/content-block-css/src/settings.ts, packages/cli/templates/content-block-tailwind/src/settings.ts
This change fixes the deprecated dropdown types in the block templates
=> fix: deprecated dropdown types

packages/cli/README.md
=> chore: add hint to readme for local environment

.changeset/rare-schools-happen.md, packages/cli/src/commands/createPlatformApp.ts
=> chore: change from dev to serve

.changeset/six-squids-teach.md, packages/sidebar-settings/src/helpers/rules/index.ts, packages/sidebar-settings/src/helpers/rules/urlRule.ts, packages/sidebar-settings/tests/helpers/rules/urlRule.spec.ts
This PR adds the `urlRule` that validates url strings.
=> feat: add url rule

.changeset/late-ears-obey.md, packages/sidebar-settings/src/helpers/rules/minimumNumericalOrPixelRule.ts, packages/sidebar-settings/tests/helpers/rules/minimumNumericalOrPixelRule.spec.ts
This PR adds the minimumNumericalOrPixelRule
=> feat: add minimumNumericalOrPixelRule

packages/app-bridge/src/registries/api/GetAssetBulkDownloadToken.ts
Reverts https://github.com/Frontify/brand-sdk/pull/646
=> chore: revert function rename

.changeset/mighty-maps-clap.md
=> chore: stable release of app-bridge

.changeset/olive-goats-nail.md, packages/cli/src/utils/verifyManifest.ts
- Added optional to assetAction as otherwise there is always an assetAction needed in the manfiest
=> chore: add optional to assetAction

.changeset/small-kiwis-tap.md, packages/cli/src/utils/verifyManifest.ts
- changed naming to align with the web-app wording.
=> chore: change naming to workspace

.changeset/gorgeous-baboons-run.md, packages/cli/templates/platform-app-css-modules/manifest.json, packages/cli/templates/platform-app-css/manifest.json, packages/cli/templates/platform-app-tailwind/manifest.json
- Adapt manifest to follow the new manifest structure
=> chore: update platform app manifest

README.md, packages/app-bridge/CHANGELOG.md, packages/app-bridge/package.json, packages/app-bridge/src/AppBridgeTheme.ts, packages/app-bridge/src/react/usePageTemplateSettings.spec.ts, packages/app-bridge/src/react/usePageTemplateSettings.ts, packages/app-bridge/src/react/useTemplateAssets.spec.ts, packages/app-bridge/src/react/useTemplateAssets.ts, packages/app-bridge/src/react/useThemeAssets.spec.ts, packages/app-bridge/src/react/useThemeAssets.ts, packages/app-bridge/src/react/useThemeSettings.spec.ts, packages/app-bridge/src/react/useThemeSettings.ts, packages/app-bridge/src/tests/AppBridgeThemeStub.ts, packages/app-bridge/src/types/Emitter.ts, packages/app-bridge/src/types/ThemeTemplate.ts, packages/app-bridge/src/types/index.ts, packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/deploy.ts, packages/cli/src/utils/compiler.ts, packages/cli/src/utils/verifyManifest.ts, packages/cli/templates/platform-app-css-modules/manifest.json, packages/cli/templates/platform-app-css/manifest.json, packages/cli/templates/platform-app-tailwind/manifest.json, packages/cli/tests/utils/verifyManifest.spec.ts, packages/guideline-blocks-settings/CHANGELOG.md, packages/guideline-blocks-settings/package.json, packages/sidebar-settings/CHANGELOG.md, packages/sidebar-settings/package.json, pnpm-lock.yaml
Syncs main to dev, so it has the latest state and v4 can build upon this and I can finish up: https://github.com/Frontify/brand-sdk/pull/657
Note: we should automate that, as far as possible, so at least the PR opens automatically.
=> chore: syncs main to dev

.changeset/cuddly-flies-promise.md, packages/guideline-blocks-settings/src/components/Attachments/AttachmentItem.tsx, packages/guideline-blocks-settings/src/components/Attachments/Attachments.tsx, packages/guideline-blocks-settings/src/components/Attachments/types.ts
[Task](https://app.clickup.com/t/8693gv7m9)
=> feat: replace attachment download with tracked download

CODEOWNERS
Proposal to adjust the `CODEOWNERS` to split everything to what should be owned by each team. 
Pair (programmed) with: @mike85
=> chore: codeowners file

.github/workflows/continuous-deployment.yml
Fixes typo that brokes the continous deployment ci
=> fix: continuous-deployment ci

.changeset/eleven-spiders-pretend.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
Adds new property to manifest.json check for Platform Apps. 
-> Now requires a title to be present.
=> feat: add title to manifest.json of platform Apps

packages/app-bridge/src/AppBridgePlatformApp.ts
-> need to refactor constants to align with the manifest
=> refactor: align string constants with cli

.changeset/stale-hairs-wash.md, packages/app-bridge/src/AppBridgeBlock.ts, packages/app-bridge/src/tests/AppBridgeBlockStub.ts
=> feat: remove deprecated functions on appBridgeBlock

.changeset/afraid-trees-mate.md, packages/guideline-blocks-settings/src/hooks/useAttachments.tsx
https://app.clickup.com/t/8693nbz40
=> fix: useAttachments use the correct functions, for adding and removing

.changeset/two-pillows-walk.md, packages/guideline-blocks-settings/src/settings/background.ts
Add label and move type so that jsdoc is correctly applied for function
=> feat: add label option to getBackgroundSettings

.changeset/hungry-timers-punch.md, packages/cli/src/commands/login.ts
=> fix: nested template literals and typo

.changeset/chatty-parents-kiss.md, packages/app-bridge/src/AppBridgeTheme.ts
Add theme template context to appBridgeThemes context.
=> feat: add theme template context to appBridgeThemes context

CODEOWNERS, packages/platform-app/.eslintrc.js, packages/platform-app/.gitignore, packages/platform-app/.prettierrc, packages/platform-app/README.md, packages/platform-app/package.json, packages/platform-app/src/index.ts, packages/platform-app/src/platformApps.ts, packages/platform-app/tsconfig.json, packages/platform-app/tsconfig.node.json, packages/platform-app/vite.config.ts, pnpm-lock.yaml
- Adds the Platform App package to the brand-sdk
=> feat: add platform-app package and adjust codeowners

.changeset/kind-fishes-flash.md, .github/workflows/guideline-blocks-continuous-integration.yml, CODEOWNERS, packages/app-bridge/CHANGELOG.md, packages/app-bridge/src/AppBridgeTheme.ts, packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/deploy.ts, packages/cli/src/commands/login.ts, packages/cli/src/index.ts, packages/cli/src/utils/user.ts, packages/cli/tests/utils/user.spec.ts, packages/guideline-blocks-settings/CHANGELOG.md, packages/guideline-blocks-settings/package.json, packages/guideline-blocks-settings/src/hooks/useAttachments.tsx, packages/guideline-blocks-settings/src/settings/background.ts, packages/platform-app/.eslintrc.js, packages/platform-app/.gitignore, packages/platform-app/.prettierrc, packages/platform-app/README.md, packages/platform-app/package.json, packages/platform-app/src/index.ts, packages/platform-app/src/platformApps.spec.ts, packages/platform-app/src/platformApps.ts, packages/platform-app/tsconfig.json, packages/platform-app/tsconfig.node.json, packages/platform-app/vite.config.ts, pnpm-lock.yaml
- Includes template to AppBridgeTheme context
=> feat: AppBridgeThemes update context to include template

packages/guideline-blocks-settings/package.json, packages/guideline-blocks-settings/setupTests.ts, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/AttachmentsToolbarButton/AttachmentsToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/AttachmentsToolbarButton/AttachmentsToolbarButtonTrigger.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/BaseToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/DragHandleToolbarButton/DragHandleToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/FlyoutToolbarButton/FlyoutToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/MenuToolbarButton/MenuToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/MenuToolbarButton/ToolbarFlyoutMenu.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/Toolbar.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/ToolbarButton/ToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/hooks/useMultiFlyoutState.spec.tsx, packages/guideline-blocks-settings/src/hooks/useAttachments.spec.tsx, packages/guideline-blocks-settings/tsconfig.json, pnpm-lock.yaml
Test new toolbar components and add jest-dom matchers for vitest
=> test: toolbar components

.changeset/cuddly-pets-hammer.md, packages/app-bridge/src/AppBridgeTheme.ts
This PR fixes an incorrect return type
=> fix: document page duplication return type

.changeset/curly-foxes-heal.md, packages/cli/templates/platform-app-css-modules/package.json, packages/cli/templates/platform-app-css/package.json, packages/cli/templates/platform-app-tailwind/package.json, packages/cli/templates/platform-app-tailwind/src/index.ts
Applies the reverted changes to main where they belong
=> fix: adjust templates (#786)

.changeset/eight-flies-cross.md, .changeset/grumpy-dolphins-perform.md, package.json, packages/cli/templates/platform-app-css-modules/package.json, packages/cli/templates/platform-app-css/package.json, packages/cli/templates/platform-app-tailwind/package.json, packages/guideline-blocks-settings/package.json, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/components/FloatingButton/EditButtonModal/EditModal.tsx, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/EditLinkModal/EditModal.tsx, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/InsertLinkModal/InsertModal.tsx, packages/sidebar-settings/package.json, pnpm-lock.yaml
- Update to 12.0.0-beta.411
- Replace RTE floating modal div with FloatingModalWrapper
=> feat: replace content with floating modal wrapper

.changeset/wild-bags-judge.md, packages/app-bridge/src/AppBridgeTheme.ts, packages/app-bridge/src/registries/commands/CommandRegistry.ts, packages/app-bridge/src/registries/commands/NavigateToDocumentSection.ts, packages/app-bridge/src/registries/commands/index.ts
Adds `navigateToDocumentSection` command to the AppBridgeTheme
CU-8693yma45
=> feat: add navigateToDocumentSection command to AppBridgeTheme

.changeset/wild-bags-judge.md, packages/app-bridge/src/AppBridgeTheme.ts, packages/app-bridge/src/registries/commands/CommandRegistry.ts, packages/app-bridge/src/registries/commands/NavigateToDocumentSection.ts, packages/app-bridge/src/registries/commands/index.ts
* feat: add navigateToDocumentSection command to AppBridgeTheme
* changeset
=> feat: add navigateToDocumentSection command to AppBridgeTheme (#807)

.changeset/violet-ligers-sort.md, packages/guideline-blocks-settings/src/components/RichTextEditor/RichTextEditor.tsx
Only resetting on switch to view-mode as setting on edit mode is unnecessary
=> fix: reset viewport state

.changeset/fresh-steaks-dream.md
Adds the missing changeset of https://github.com/Frontify/brand-sdk/pull/819
=> fix: add missing changeset

.changeset/smart-walls-ring.md, packages/app-bridge/src/AppBridgeBlock.ts, packages/app-bridge/src/tests/AppBridgeBlockStub.ts
Adding this option to v3 as well as v4 as the type signature changes caused by this update in v4 only cause a lot of type compatibility issues.
=> feat: appBridgeBlock isAuthenticated context

.changeset/smart-suns-type.md, package.json, packages/app-bridge/CHANGELOG.md, packages/app-bridge/src/AppBridgeBlock.ts, packages/app-bridge/src/react/useBlockSettings.ts, packages/app-bridge/src/tests/AppBridgeBlockStub.ts, packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/utils/verifyManifest.ts, packages/cli/templates/platform-app-css-modules/package.json, packages/cli/templates/platform-app-css/package.json, packages/cli/templates/platform-app-tailwind/package.json, packages/cli/tests/utils/verifyManifest.spec.ts, packages/guideline-blocks-settings/CHANGELOG.md, packages/guideline-blocks-settings/package.json, packages/guideline-blocks-settings/src/components/RichTextEditor/RichTextEditor.spec.ct.tsx, packages/guideline-blocks-settings/src/components/RichTextEditor/RichTextEditor.tsx, packages/guideline-blocks-settings/src/hooks/useIsInViewport.spec.ts, packages/guideline-blocks-settings/src/hooks/useIsInViewport.ts, packages/platform-app/CHANGELOG.md, packages/platform-app/package.json, packages/sidebar-settings/CHANGELOG.md, packages/sidebar-settings/package.json, pnpm-lock.yaml
Just merging v3 changes to v4, so we can release also an updated version of v4
=> feat: merge main to dev for v11

.changeset/clever-gifts-join.md, CODEOWNERS, packages/app-bridge/src/AppBridgePlatformApp.ts, packages/app-bridge/src/registries/api/ApiMethodRegistry.ts, packages/app-bridge/src/registries/api/GetProxyNetworkCall.spec.ts, packages/app-bridge/src/registries/api/GetProxyNetworkCall.ts, packages/app-bridge/src/registries/api/index.ts
Add `getProxyNetworkCall` to AppBridge
Clickup Task : https://app.clickup.com/t/869400pzp
=> feat(appBridge): Add proxyNetworkCall method

packages/app-bridge/src/react/useDocumentCategories.spec.ts, packages/app-bridge/src/react/useGroupedDocuments.spec.ts
Fixes some flaky tests in `useGroupedDocuments` and `useDocumentCategories`
=> fix: useGroupedDocuments and useDocumentCategories flaky tests

.changeset/honest-rockets-cheat.md, packages/app-bridge/src/AppBridgePlatformApp.ts
-> move also appBridge 3 versions to v4
=> fix: move up to v4

.changeset/seven-beds-dance.md, packages/guideline-blocks-settings/src/settings/border.ts
https://app.clickup.com/t/86945rfyz
=> fix(settings): border settings does not add px automatically

.changeset/forty-ligers-melt.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
-> naming update to reflect updates to the domain model of the [remote Service](https://www.figma.com/file/HVPqFN8juop6itsIFC2EWl/T1-2024-(January---April)?type=whiteboard&node-id=2262%3A11161&t=ptcR0p5CukIqofQs-1).
=> fix: update naming to fit network endpoints naming

.changeset/tidy-seas-juggle.md, packages/platform-app/src/platformApps.ts
- Restrict Platform App Settings choices and disable access to setting choices that have links to guidelines.
=> feat: restrict settings options [CU-86945y30m]

.changeset/thirty-badgers-mate.md, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/Toolbar.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/Toolbar.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/ToolbarSegment.tsx
To get rid of that right border.
=> fix(BlockItemWrapper): hide toolbar segment if there are no items

packages/app-bridge/src/AppBridgePlatformApp.ts, packages/app-bridge/src/helpers/index.ts, packages/app-bridge/src/helpers/navigation.spec.ts, packages/app-bridge/src/helpers/navigation.ts, packages/app-bridge/src/react/useDocumentSection.spec.ts, packages/app-bridge/src/react/useDocumentSection.ts, packages/app-bridge/src/tests/AppBridgeBlockStub.ts, packages/app-bridge/src/tests/DocumentSectionApiDummy.ts, packages/app-bridge/src/tests/DocumentSectionDummy.ts, packages/app-bridge/src/types/DocumentSection.ts, packages/app-bridge/src/types/Emitter.ts
v4 should only contains breaking changes of things that are already out (makes it easier to release the v4)
=> feat: apply changes wrongly done in v4 into v3

.changeset/two-spies-swim.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
-> adding unique constraint to keep Secret Key and Endpoint Name unique.
=> feat: add secret and endpoint restrictions

packages/app-bridge/src/react/index.ts, packages/app-bridge/src/react/useDocumentNavigation.spec.ts, packages/app-bridge/src/react/useDocumentNavigation.ts, packages/app-bridge/src/registries/api/ApiMethodRegistry.ts, packages/app-bridge/src/tests/DocumentNavigationTreeDummy.ts, packages/app-bridge/src/tests/index.ts, packages/app-bridge/src/types/Guideline.ts
This PR adds the react hook for getting the document navigation items.
=> feat: add `useDocumentNavigation` hook

.changeset/lucky-taxis-kneel.md, packages/app-bridge/src/AppBridgePlatformApp.spec.ts, packages/app-bridge/src/AppBridgePlatformApp.ts
-> Adjustments to make userState and settings available through appBridge.state(*)
=> feat: add user state variable

.changeset/fifty-dodos-poke.md, packages/guideline-blocks-settings/src/components/BlockItemWrapper/BlockItemWrapper.tsx
Wrapped the whole component in a memo. No other changes.
=> feat(BlockItemWrapper): memoize component

.changeset/four-crabs-bake.md, packages/app-bridge/src/tests/AppBridgeThemeStub.ts
this change enables some hooks to be updated with no changes (or minimal changes) on tests
CU-8694gp396
=> feat: update appBridgeThemeStub w context/state

.changeset/tame-bikes-design.md, packages/app-bridge/src/tests/GuidelineSearchResultApiDummy.ts, packages/app-bridge/src/types/GuidelineSearchResult.ts
GuidelineSearchResultApi: Added additional prop. The prop is need on the web app for analytics
=> fix: Added additional prop

.changeset/tough-coats-begin.md, package.json, packages/app-bridge/src/repositories/AssetRepository.ts, packages/app-bridge/src/tests/AssetApiDummy.ts, packages/app-bridge/src/tests/AssetChooserResultDummy.ts, packages/app-bridge/src/tests/AssetDummy.ts, packages/app-bridge/src/types/Asset.ts
Needs this: https://github.com/Frontify/web-app/pull/4132
Need this backgroundColor to fix this: https://app.clickup.com/t/2523021/TASK-11147
=> feat: add backgroundColor to asset

.changeset/stupid-coins-grin.md, packages/app-bridge/src/AppBridgeBlock.ts, packages/app-bridge/src/react/index.ts, packages/app-bridge/src/react/useAfterInsertion.spec.tsx, packages/app-bridge/src/react/useAfterInsertion.tsx, packages/app-bridge/src/tests/AppBridgeBlockStub.ts, pnpm-lock.yaml
Related Pr in web-app (adds properties to v3 AND v4): https://github.com/Frontify/web-app/pull/4012
=> feat: add new useAfterInsertion hook

.changeset/tough-elephants-play.md, package.json, packages/app-bridge/src/repositories/AssetRepository.ts, packages/app-bridge/src/tests/AssetApiDummy.ts, packages/app-bridge/src/tests/AssetChooserResultDummy.ts, packages/app-bridge/src/tests/AssetDummy.ts, packages/app-bridge/src/types/Asset.ts
Part of [TASK-11183](https://app.clickup.com/t/2523021/TASK-11183)
=> feat: add isDownloadProtected to asset

.changeset/light-moons-count.md, packages/app-bridge/src/react/useAssetViewer.spec.tsx, packages/app-bridge/src/react/useAssetViewer.ts, packages/app-bridge/src/registries/commands/AssetViewer.ts, packages/app-bridge/src/registries/commands/CommandRegistry.ts, packages/app-bridge/src/types/Emitter.ts, packages/app-bridge/src/types/Terrific.ts
This has been missing for quite a while and is a first step to solve the following tickets:
https://app.clickup.com/t/2523021/TASK-10984
https://app.clickup.com/t/8693wz874
https://app.clickup.com/t/2523021/TASK-11183
=> feat(assetViewer): add isDownloadable option to asset viewer

.changeset/blue-lions-brush.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
-> Restricts regex to not include hyphens.
=> fix: adjust regex to be more strict 

.changeset/short-apricots-buy.md, .github/workflows/app-bridge-continuous-integration.yml, .github/workflows/cli-continuous-integration.yml, .github/workflows/continuous-deployment.yml, .github/workflows/guideline-blocks-continuous-integration.yml, .github/workflows/typing-continuous-integration.yml, package.json, packages/cli/templates/platform-app-css-modules/package.json, packages/cli/templates/platform-app-css-modules/tsconfig.json, packages/cli/templates/platform-app-css-modules/tsconfig.node.json, packages/cli/templates/platform-app-css/package.json, packages/cli/templates/platform-app-css/tsconfig.json, packages/cli/templates/platform-app-css/tsconfig.node.json, packages/cli/templates/platform-app-tailwind/package.json, packages/cli/templates/platform-app-tailwind/tsconfig.json, packages/cli/templates/platform-app-tailwind/tsconfig.node.json, pnpm-lock.yaml
=> fix: eslint config in platform app templates

.changeset/sour-kangaroos-tease.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
=> chore: Limit secret length

.changeset/clever-suns-laugh.md, packages/app-bridge/src/registries/api/GetSecretRequest.spec.ts, packages/app-bridge/src/registries/api/GetSecretRequest.ts
-> possible rename for the method name
=> chore: rename brand sdk name

.changeset/spicy-books-shout.md, packages/app-bridge/src/registries/api/GetSecureRequest.ts
-> adjusts the secure request response
=> feat: adjust secure request response

.changeset/breezy-wolves-sit.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
- adds new field to manifest.json
=> feat: add new property to manifest

.changeset/curvy-cheetahs-collect.md, packages/guideline-blocks-settings/package.json, packages/guideline-blocks-settings/tailwind.config.ts, pnpm-lock.yaml
[CSS variables are not supported in media queries](https://stackoverflow.com/questions/40722882/css-native-variables-not-working-in-media-queries). Because of this I did not add the CSS variables for each breakpoint, as I don't think they could be consumed either by us or our partners.
We can enable our partners by providing a shared tailwind config that they can reuse.
=> feat(tailwind): introduce container queries

.changeset/serious-donuts-clap.md, packages/cli/package.json, packages/cli/src/commands/serve.ts, packages/cli/src/index.ts, pnpm-lock.yaml
- Adjusts Platform App serve Command to serve settings.ts on the side
=> feat: add additional build step for settings

.changeset/gentle-pots-deny.md, packages/cli/templates/platform-app-css-modules/.gitignore, packages/cli/templates/platform-app-css-modules/.secret-example.json, packages/cli/templates/platform-app-css-modules/index.html, packages/cli/templates/platform-app-css-modules/package.json, packages/cli/templates/platform-app-css-modules/src/App.tsx, packages/cli/templates/platform-app-css/.gitignore, packages/cli/templates/platform-app-css/.secret-example.json, packages/cli/templates/platform-app-css/index.html, packages/cli/templates/platform-app-css/package.json, packages/cli/templates/platform-app-css/src/App.tsx, packages/cli/templates/platform-app-tailwind/.gitignore, packages/cli/templates/platform-app-tailwind/.secret-example.json, packages/cli/templates/platform-app-tailwind/index.html, packages/cli/templates/platform-app-tailwind/package.json, packages/cli/templates/platform-app-tailwind/src/App.tsx
=> chore: update templates

.changeset/witty-tools-check.md, packages/app-bridge/src/react/usePlatformAppBridge.ts
-> add simple notice to inform about deprecation (there shouldnt be any usage of this, but just in case).
=> feat: deprecate react hooks

.changeset/wild-students-grow.md, packages/app-bridge-app/package.json, packages/app-bridge-app/src/AppBridgePlatformApp.ts, packages/app-bridge-app/src/index.ts, packages/app-bridge-app/src/react/appContext.spec.tsx, packages/app-bridge-app/src/react/appContext.ts, packages/app-bridge-app/src/react/appSettings.spec.tsx, packages/app-bridge-app/src/react/appSettings.ts, packages/app-bridge-app/src/react/appUserState.spec.tsx, packages/app-bridge-app/src/react/appUserState.ts, packages/app-bridge-app/vite.config.mts
-> adds typing for get, set (subscribe is missing)
=> feat: add typed settings and userState

.changeset/tough-peas-hide.md, packages/app-bridge-app/package.json
-> adds correct files to exported package
=> chore: add exports

.changeset/neat-pets-thank.md, package.json, packages/app-bridge-app/src/AppBridgePlatformApp.ts
-> adds pnpm build:app-bridge-app to the build step
=> chore: update app-bridge-app

.changeset/spotty-sheep-jam.md, packages/app-bridge-app/src/registries/api/GetAccountId.spec.ts
for some reason it didnt create the changeset file.
=> chore: adjust test

.changeset/shiny-poets-enjoy.md, .github/workflows/app-bridge-theme-continuous-integration.yml, packages/app-bridge-theme/src/react/useLanguage.spec.ts, packages/app-bridge-theme/src/react/useLanguage.ts
https://app.clickup.com/t/869524b7y
=> feat(AppBridgeTheme): add use language hook

.changeset/tasty-coins-jam.md, packages/app-bridge-theme/src/index.ts, packages/app-bridge-theme/src/react/index.ts, packages/app-bridge-theme/src/react/useIsEditing.spec.ts, packages/app-bridge-theme/src/react/useIsEditing.ts, packages/app-bridge-theme/src/react/useLanguage.spec.ts, packages/app-bridge-theme/src/react/useLanguage.ts
https://app.clickup.com/t/869524b7y
=> feat: add useIsEditing hook

.changeset/long-dancers-fold.md, packages/app-bridge-app/src/index.ts, packages/app-bridge-app/src/types/index.ts
=> feat: Export types from `Api.ts`

.changeset/pink-cycles-leave.md, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/components/FloatingButton/EditButtonModal/EditModal.spec.tsx, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/ButtonPlugin/components/FloatingButton/EditButtonModal/EditModal.tsx, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/EditLinkModal/EditModal.spec.tsx, packages/guideline-blocks-settings/src/components/RichTextEditor/plugins/LinkPlugin/FloatingLink/EditLinkModal/EditModal.tsx
https://app.clickup.com/t/86953m74n
=> feat(RTE): make link clickable in edit modal

.changeset/kind-peaches-teach.md, packages/guideline-blocks-settings/src/components/BlockInjectButton/BlockInjectButton.tsx
https://app.clickup.com/t/869542qa5
=> fix(BlockInjectButton): menu is opening in top left

.changeset/mean-rings-drum.md, packages/sidebar-settings/src/blocks/fontInput.ts
`highlightBorderWeightCustomEnabled` must be `boolean` and not `string`
=> fix: fontValue type fix

.changeset/swift-ladybugs-happen.md, packages/sidebar-settings/src/blocks/fontInput.ts
reverts https://github.com/Frontify/brand-sdk/pull/1059
=> fix: revert fontvalue types from dev

.changeset/twelve-keys-begin.md, packages/app-bridge-theme/src/types/Context.ts
=> feat(AppBridgeTheme): added list of enabled features to context

.changeset/tricky-rocks-provide.md, packages/app-bridge-app/src/registries/api/ExecuteGraphQl.ts
This PR adds an option to run beta GraphQL requests.
=> feat: Add option to make beta GraphQL request

.changeset/fifty-cougars-knock.md, packages/platform-app/package.json, packages/platform-app/src/platformApps.ts, pnpm-lock.yaml
-> uses app-bridge-app instead of app-bridge
=> chore: adjust import

.changeset/soft-mugs-peel.md, packages/app-bridge-theme/src/react/useEnabledFeatures.spec.ts, packages/app-bridge-theme/src/react/useEnabledFeatures.ts
=> feat: add useEnabledFeatures

.changeset/slimy-cats-repeat.md, packages/app-bridge-theme/src/react/index.ts
=> fix: export useEnabledFeatures hook

packages/platform-app/package.json, packages/platform-app/src/platformApps.ts, pnpm-lock.yaml
-> needed on the dev branch to fix the typecheck
=> chore: fix dev branch

.changeset/pink-houses-pump.md, packages/cli/src/utils/compiler.ts, packages/cli/tests/utils/compiler.spec.ts
-> New Build for Platform apps that build a complete folder and upload the folder content to the Marketplace.
=> feat: adjust build for PlatformApps to upload Folders

.changeset/poor-shrimps-live.md, packages/guideline-blocks-settings/package.json, packages/guideline-blocks-settings/src/components/Attachments/Attachments.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/AttachmentsToolbarButton/AttachmentsToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/DragHandleToolbarButton/DragHandleToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/DragHandleToolbarButton/DragHandleToolbarButton.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/FlyoutToolbarButton/FlyoutToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/MenuToolbarButton/MenuToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/ToolbarButton/ToolbarButton.spec.tsx, packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/ToolbarButtonTooltip.tsx, packages/guideline-blocks-settings/src/components/DownloadButton/DownloadButton.tsx
=> refactor: replace legacyTooltip

.changeset/twenty-pumas-pump.md, packages/app-bridge-theme/src/registries/EventRegistry.ts, packages/app-bridge-theme/src/registries/index.ts, packages/app-bridge-theme/src/types/Event.ts
https://app.clickup.com/t/8695hqhaq
=> refactor(AppBridgeTheme): remove EventRegistry

.changeset/hot-queens-chew.md, package.json, packages/cli/templates/platform-app-css-modules/package.json, packages/cli/templates/platform-app-css/package.json, packages/cli/templates/platform-app-tailwind/package.json, packages/guideline-blocks-settings/package.json, packages/sidebar-settings/package.json, pnpm-lock.yaml
=> chore: bump fondue

.changeset/sour-cheetahs-buy.md, packages/guideline-themes/src/index.ts
https://app.clickup.com/t/8695hb071
=> refactor(GuidelineThemes): type cleanup

.changeset/spicy-candles-yell.md, packages/cli/src/utils/verifyManifest.ts
-> To enable a surface in the library we add the guidelines as type.
=> feat: add guideline to verifier

.changeset/gorgeous-cherries-wink.md, packages/app-bridge-app/src/AppBridgePlatformApp.ts
-> removes extensions from bulkActions selection
=> feat: remove extensions from context object

.changeset/slimy-rats-cross.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
-> Adds assetBulkactions with filenameExtensions.
=> feat: add assetBulkActions to manifest

.changeset/fifty-eels-admire.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
-> Due to feedback it would allow to use secrets in the host of the resource
=> fix: update to be able to use strings

.changeset/wet-feet-walk.md, packages/app-bridge/src/types/Document.ts, packages/app-bridge/src/types/Terrific.ts, packages/sidebar-settings/src/blocks/index.ts
Needs to be merged done to v4-alpha and then web-app needs adjustments for it
=> refactor: remove PatternLibrary

.changeset/strange-maps-deliver.md, packages/cli/templates/platform-app-css-modules/package.json, packages/cli/templates/platform-app-css/package.json, packages/cli/templates/platform-app-tailwind/package.json
Updates templates to newest package versions.
=> chore: update to latest app-bridge

.changeset/witty-jeans-search.md, packages/guideline-blocks-settings/package.json, pnpm-lock.yaml
need to reopen as I fucked up something in the first one
=> chore(GuidelineBlockSettings): bump dnd-kit

.changeset/nine-bees-doubt.md, packages/guideline-blocks-settings/tailwind.config.ts
So the blocks don't overwrite web-app styles on that level
https://app.clickup.com/t/2523021/TASK-13317
=> fix(guidelineBlocksSettings): tailwind base

.changeset/dull-badgers-brake.md, packages/cli/src/servers/platformAppDevelopmentServer.ts
Adds explicit Cors header to vitest config.
=> fix: add explicit cors

.changeset/gorgeous-games-dream.md, packages/cli/src/utils/verifyManifest.ts, packages/cli/tests/utils/verifyManifest.spec.ts
=> chore: update zod

.github/workflows/continuous-deployment.yml
Based on this
https://github.com/changesets/action/issues/98#issuecomment-2519457411
=> fix(CI): publish is not working

.changeset/khaki-ants-stare.md, packages/sidebar-settings/src/blocks/choices.ts
[CU-8698nzzxe](https://app.clickup.com/t/8698nzzxe)
=> feat(sidebar-settings): add optional aria-label to Choice type

.changeset/purple-seahorses-watch.md, packages/app-bridge-theme/src/react/index.ts, packages/app-bridge-theme/src/react/useActiveSectionHeadingId.spec.ts, packages/app-bridge-theme/src/react/useActiveSectionHeadingId.ts, packages/app-bridge-theme/src/types/Context.ts
https://app.clickup.com/t/8698ucgmr
=> feat: app bridge theme active section heading context

.changeset/heavy-scissors-approve.md, packages/app-bridge-app/src/AppBridgePlatformApp.ts
Adds the new context for the navigation action surface
=> feat: add NavigationAction Context

.changeset/nice-weeks-develop.md, packages/app-bridge-app/src/AppBridgePlatformApp.ts
Adds themeAction and its properties as a type to the surface inside of the app.
=> feat: adds themeAction to appBridge PlatformApp context

.changeset/old-cougars-study.md, packages/app-bridge/src/repositories/AssetRepository.ts, packages/app-bridge/src/tests/AssetApiDummy.ts, packages/app-bridge/src/tests/AssetChooserResultDummy.ts, packages/app-bridge/src/tests/AssetDummy.ts, packages/app-bridge/src/types/Asset.ts
=> feat: add alt text to asset

.changeset/happy-brooms-camp.md, packages/guideline-blocks-settings/src/components/DownloadButton/DownloadButton.spec.ct.tsx, packages/guideline-blocks-settings/src/components/DownloadButton/DownloadButton.tsx, packages/guideline-blocks-settings/src/components/DownloadButton/types.ts
=> feat(DownloadButton): add prop for custom aria label

.changeset/heavy-cats-lay.md, packages/app-bridge-app/src/registries/api/ExecuteGraphQl.ts
This PR allows enable feature previews on GQL request calls.
=> feat(app): Enable to pass preview features to the GQL calls

.changeset/heavy-cats-lay.md, packages/app-bridge-app/src/registries/api/ExecuteGraphQl.ts
=> Revert "feat(app): Enable to pass preview features to the GQL calls"

packages/guideline-blocks-settings/src/components/BlockInjectButton/BlockInjectButton.spec.ct.tsx, packages/guideline-blocks-settings/src/components/BlockInjectButton/BlockInjectButton.tsx
Will bump changeset after all components have been replaced.
=> refactor(BlockInjectButton): replace deprecated fondue components

packages/guideline-blocks-settings/src/components/BlockItemWrapper/Toolbar/FlyoutToolbarButton/FlyoutToolbarButton.tsx
Will need:
https://github.com/Frontify/guideline-blocks/pull/1136
=> refactor(FlyoutToolbarButton): replace legacy fondue components

.changeset/tough-spoons-press.md, packages/app-bridge-app/src/utilities/MessageBus.ts
**What**
Increases Timeout of message bus
=> feat: increase timeout of message bus

.changeset/loud-poems-yawn.md, packages/app-bridge-theme/src/registries/CommandRegistry.ts, packages/app-bridge-theme/src/registries/commands/ScrollPageToTop.ts, packages/app-bridge-theme/src/registries/commands/index.ts
This PR adds a new "scroll page to top" command to the AppBridgeTheme package
CU-8698ywm46
=> feat(AppBridgeTheme): scroll page to top command
